import {
  ensureSignedInWithFabric,
  initEmbeddedAuth,
} from '@microsoft/rayfin-auth-provider-fabric';
import { RayfinClient } from '@microsoft/rayfin-client';

import type { AppSchema } from '@instance';

const env = import.meta.env;

if (!env.VITE_RAYFIN_API_URL || !env.VITE_RAYFIN_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing VITE_RAYFIN_* config. `.env.local` is generated by `rayfin env --framework vite`, ' +
      'which `npm run dev` runs for you.'
  );
}

/**
 * True when the API is the local Docker backend rather than deployed Fabric.
 *
 * `127.0.0.1` counts: `rayfin up` adds it to `allowedRedirectUris` alongside
 * `localhost`, so it is a origin someone will legitimately use. Matching only
 * the word "localhost" would send the local stack down the Fabric SSO path.
 */
const LOCAL_HOSTS = new Set(['localhost', '127.0.0.1', '[::1]', '::1']);
export const isLocalBackend = LOCAL_HOSTS.has(new URL(env.VITE_RAYFIN_API_URL).hostname);

/**
 * True when the app is running inside the Fabric portal's iframe.
 *
 * There the host chrome owns identity: it displays the signed-in account and
 * handed this app its session by `postMessage`. The UI uses this to drop its
 * own account menu — an in-app "sign out" in that mode would end only the
 * Rayfin session, not the portal session that produced it, leaving a sign-in
 * screen inside a portal the user never left.
 *
 * Detection matches the SDK's documented contract: the portal opens the
 * iframe with `?fabricEmbedded=true`, and the SDK persists the same flag to
 * sessionStorage under the same name so it survives client-side URL cleanup.
 * The SDK's own `isEmbeddedMode` helper is typed in its .d.ts but missing
 * from the package's runtime exports (1.34.0), so the check is written out
 * here rather than deep-imported from `dist/`.
 */
export const isEmbedded = (() => {
  if (new URLSearchParams(window.location.search).get('fabricEmbedded') === 'true') return true;
  try {
    return sessionStorage.getItem('fabricEmbedded') === 'true';
  } catch {
    return false; // sessionStorage can be unavailable in sandboxed iframes
  }
})();

export const client = new RayfinClient<AppSchema>({
  baseUrl: env.VITE_RAYFIN_API_URL.endsWith('/')
    ? env.VITE_RAYFIN_API_URL
    : `${env.VITE_RAYFIN_API_URL}/`,
  publishableKey: env.VITE_RAYFIN_PUBLISHABLE_KEY,
  authStorage: true,
});

/**
 * Pin the tenant on the portal URL.
 *
 * The SDK builds its broker URL from `fabricPortalUrl` and carries no tenant
 * hint of its own. Opened bare, `app.fabric.microsoft.com` resolves to whichever
 * Microsoft account the browser is already signed into — so anyone whose default
 * session is a personal account, or a different tenant, gets the portal's
 * `HTTP Error 401 / Signed in as …` page instead of a sign-in prompt. Nothing
 * identifies the cause as a tenant mismatch.
 *
 * `FabricAuthOptions.fabricPortalUrl` is documented to preserve existing query
 * parameters, so `ctid` is the supported way to say which tenant is meant. It is
 * the same hint the portal deep-link in `rayfin up status` carries.
 */
function portalUrlForTenant(): string {
  if (!env.VITE_FABRIC_PORTAL_URL) {
    // Named, because the bare alternative is `TypeError: Invalid URL` with no
    // hint which of the VITE_* variables is missing.
    throw new Error('VITE_FABRIC_PORTAL_URL is not set — re-run `rayfin env --framework vite`.');
  }
  const url = new URL(env.VITE_FABRIC_PORTAL_URL);
  if (env.VITE_FABRIC_TENANT_ID) url.searchParams.set('ctid', env.VITE_FABRIC_TENANT_ID);
  return url.toString();
}

// Built lazily: the local backend never uses these, so a missing portal URL
// must not stop the local app from even loading.
const fabricOptions = () => ({
  workspaceId: env.VITE_FABRIC_WORKSPACE_ID,
  projectId: env.VITE_FABRIC_ITEM_ID,
  fabricPortalUrl: portalUrlForTenant(),
  returnOrigin: window.location.origin,
});

/**
 * Sign in to the local Docker backend, which has no Entra at all, using a
 * fixture account created on first run. Nothing to type. These credentials only
 * ever reach a container on the developer's own machine.
 */
async function signInLocal(): Promise<void> {
  const credentials = { email: 'dev@contoso.com', password: 'LocalDev!Pass123' };
  try {
    await client.auth.signIn(credentials);
  } catch (err) {
    // INVALID_GRANT is also how the backend reports "no such user".
    if ((err as { code?: string })?.code !== 'INVALID_GRANT') throw err;
    await client.auth.signUp(credentials);
    await client.auth.signIn(credentials);
  }
}

/**
 * Get a session without asking the user for anything. Safe on page load: none
 * of these paths opens a window.
 *
 * Nothing is returned: the session lands in `client.auth.getSession()`, which
 * the UI watches through `client.auth.onSessionChange`. When this resolves
 * without one, the single remaining option needs a click — running Vite on
 * localhost against *deployed* Fabric. Everywhere else it either succeeds or
 * throws: a local-backend failure surfaces as an error rather than a sign-in
 * prompt, because the local backend has no interactive sign-in to offer.
 * See {@link signIn}.
 */
export async function resumeSession(): Promise<void> {
  if (client.auth.getSession().isAuthenticated) return;

  if (isLocalBackend) return signInLocal();

  // Inside the Fabric portal the host has already signed the user in and
  // passes the session across by `postMessage`. Outside embedded mode this is
  // a no-op — one that does NOT try the refresh token (verified in the SDK
  // source), which is why the step below must stay.
  await initEmbeddedAuth(client.auth, fabricOptions());
  if (client.auth.getSession().isAuthenticated) return;

  // Against deployed Fabric the access token expires long before the refresh
  // token, and `authStorage: true` persists both. Spending it here makes
  // sign-in once per session rather than once per reload.
  if (client.auth.hasRefreshToken()) {
    await client.auth.refreshSession().catch(() => {
      // Refresh token is dead; the caller offers the sign-in button instead.
    });
  }
}

/**
 * Sign-in for a click handler, needed only when {@link resumeSession} leaves
 * the session unauthenticated.
 *
 * Against deployed Fabric the SDK opens the portal as a broker via
 * `window.open`. **Must be called from a click handler** — browsers block
 * `window.open` outside a user gesture, which is the sole reason this app has
 * a sign-in button at all. On the local backend it retries the fixture
 * sign-in instead, so the one button serves both worlds.
 */
export async function signIn(): Promise<void> {
  if (isLocalBackend) return signInLocal();
  await ensureSignedInWithFabric(client.auth, fabricOptions());
}
